openapi: 3.1.0
servers:
  - url: https://mareavida.github.io/gpt-architekt-schema
    description: GitHub Pages–Endpoint

info:
  title: GPT-Architekt Actions
  version: 1.0.0

paths:
  /create_gpt:
    post:
      operationId: createGpt
      summary: Create a new Custom GPT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGptRequest'
      responses:
        '200':
          description: GPT created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateGptResponse'

  /lint_blueprint:
    post:
      operationId: lintBlueprint
      summary: Lint and score a GPT blueprint
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              $ref: '#/components/schemas/LintBlueprintRequest'
      responses:
        '200':
          description: Lint result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LintBlueprintResponse'

  /simulate_attack:
    post:
      operationId: simulateAttack
      summary: Log a potential jailbreak or abuse attempt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulateAttackRequest'
      responses:
        '200':
          description: Attack logged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimulateAttackResponse'

  /submit_rating:
    post:
      operationId: submitRating
      summary: Submit user rating for a blueprint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitRatingRequest'
      responses:
        '200':
          description: Rating stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitRatingResponse'

components:
  schemas:
    CreateGptRequest:
      type: object
      properties:
        name:
          type: string
          description: Desired name of the new GPT
        system_prompt:
          type: string
          description: System prompt text
        developer_prompt:
          type: string
          description: Developer prompt text
        prompt_starters:
          type: array
          items:
            type: string
          description: List of starter prompts
      required:
        - name
        - system_prompt

    CreateGptResponse:
      type: object
      properties:
        gpt_id:
          type: string
        url:
          type: string

    LintBlueprintRequest:
      type: string
      description: The blueprint Markdown text

    LintBlueprintResponse:
      type: object
      properties:
        score:
          type: integer
        suggestions:
          type: array
          items:
            type: string

    SimulateAttackRequest:
      type: object
      properties:
        message:
          type: string
          description: Potentially abusive user message

    SimulateAttackResponse:
      type: object
      properties:
        logged:
          type: boolean

    SubmitRatingRequest:
      type: object
      properties:
        blueprint_id:
          type: string
        stars:
          type: integer
        comments:
          type: string

    SubmitRatingResponse:
      type: object
      properties:
        stored:
          type: boolean
